name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node: [14, 16.9, 16]
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      # Install required tools
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          check-latest: true

      # Run tests
      - name: Tests on macOS, Linux
        run: ./gradlew clean test
        if: runner.os != 'Windows'
      - name: Tests on Windows
        run: ./gradlew.bat clean test
        if: runner.os == 'Windows'
